// Legal Services Data for Lawyer Capital VA
// Organized by service, practice area, competitor, tool, and location

export const services = [
  {
    id: 'client-intake',
    name: 'Client Intake & Onboarding',
    slug: 'client-intake',
    roman: 'i',
    description: 'New client screening, conflict checks, engagement letter preparation, retainer agreement processing, initial document collection, client portal setup, intake form management, fee disclosure preparation, consultation scheduling, client onboarding packet assembly.',
    keyword: 'legal client intake virtual assistant',
    tasks: [
      'New client screening',
      'Conflict check coordination',
      'Engagement letter preparation',
      'Retainer agreement processing',
      'Initial document collection',
      'Client portal setup',
      'Intake form management',
      'Fee disclosure preparation',
      'Consultation scheduling',
      'Client onboarding packet assembly',
    ],
    tools: ['Clio', 'MyCase', 'PracticePanther', 'Lawmatics', 'Intake.me'],
  },
  {
    id: 'document-preparation',
    name: 'Document Preparation',
    slug: 'document-preparation',
    roman: 'ii',
    description: 'Pleading formatting, motion drafting support, discovery document organization, contract markup and redlining, exhibit preparation, filing-ready document assembly, template management, citation verification, document comparison, e-filing preparation.',
    keyword: 'legal document preparation virtual assistant',
    tasks: [
      'Pleading formatting',
      'Motion drafting support',
      'Discovery document organization',
      'Contract markup and redlining',
      'Exhibit preparation',
      'Filing-ready document assembly',
      'Template management',
      'Citation verification',
      'Document comparison',
      'E-filing preparation',
    ],
    tools: ['Clio', 'NetDocuments', 'iManage', 'Microsoft Word', 'Adobe Acrobat'],
  },
  {
    id: 'case-management',
    name: 'Case Management',
    slug: 'case-management',
    roman: 'iii',
    description: 'Docket tracking, deadline management, statute of limitations monitoring, case file organization, matter status reporting, court date tracking, discovery deadline management, document indexing, case timeline maintenance, opposing counsel communication logging.',
    keyword: 'legal case management virtual assistant',
    tasks: [
      'Docket tracking',
      'Deadline management',
      'Statute of limitations monitoring',
      'Case file organization',
      'Matter status reporting',
      'Court date tracking',
      'Discovery deadline management',
      'Document indexing',
      'Case timeline maintenance',
      'Opposing counsel communication logging',
    ],
    tools: ['Clio', 'MyCase', 'PracticePanther', 'Smokeball', 'CosmoLex'],
  },
  {
    id: 'court-filing',
    name: 'Court Filing & E-Filing Coordination',
    slug: 'court-filing',
    roman: 'iv',
    description: 'E-filing preparation, local court rule compliance, filing fee tracking, proof of service coordination, hearing scheduling, court calendar management, judge-specific requirement research, filing deadline tracking, certificate of service preparation, courtesy copy coordination.',
    keyword: 'court filing virtual assistant',
    tasks: [
      'E-filing preparation',
      'Local court rule compliance',
      'Filing fee tracking',
      'Proof of service coordination',
      'Hearing scheduling',
      'Court calendar management',
      'Judge-specific requirement research',
      'Filing deadline tracking',
      'Certificate of service preparation',
      'Courtesy copy coordination',
    ],
    tools: ['PACER', 'State e-filing systems', 'Clio court rules integration'],
  },
  {
    id: 'client-communication',
    name: 'Client Communication',
    slug: 'client-communication',
    roman: 'v',
    description: 'Status update emails, appointment scheduling, court date reminders, document request follow-ups, billing inquiry responses, settlement update communications, case milestone notifications, referral source thank-you letters, client satisfaction follow-ups, newsletter management.',
    keyword: 'legal client communication virtual assistant',
    tasks: [
      'Status update emails',
      'Appointment scheduling',
      'Court date reminders',
      'Document request follow-ups',
      'Billing inquiry responses',
      'Settlement update communications',
      'Case milestone notifications',
      'Referral source thank-you letters',
      'Client satisfaction follow-ups',
      'Newsletter management',
    ],
    tools: ['Clio', 'Lawmatics', 'Mailchimp', 'Practice management communication modules'],
  },
  {
    id: 'firm-administration',
    name: 'Billing & Firm Administration',
    slug: 'firm-administration',
    roman: 'vi',
    description: 'Time entry support, invoice preparation, trust account reconciliation tracking, expense management, vendor coordination, office supply ordering, bar association deadline tracking, CLE credit monitoring, firm calendar management, conflict database maintenance.',
    keyword: 'law firm virtual assistant',
    tasks: [
      'Time entry support',
      'Invoice preparation',
      'Trust account reconciliation tracking',
      'Expense management',
      'Vendor coordination',
      'Office supply ordering',
      'Bar association deadline tracking',
      'CLE credit monitoring',
      'Firm calendar management',
      'Conflict database maintenance',
    ],
    tools: ['Clio', 'QuickBooks', 'LeanLaw', 'TimeSolv', 'Tabs3'],
  },
];

export const practiceAreas = [
  {
    id: 'civil-litigation',
    name: 'Civil Litigation',
    slug: 'civil-litigation',
    description: 'Discovery management, pleading preparation, motion practice, trial coordination, settlement tracking, and document organization for civil litigation practices.',
    keyword: 'civil litigation virtual assistant',
    specialty: 'Discovery management and trial preparation support',
  },
  {
    id: 'corporate',
    name: 'Corporate & Business Law',
    slug: 'corporate',
    description: 'Contract management, M&A support, corporate filings, board meeting coordination, compliance tracking, and entity management.',
    keyword: 'corporate law virtual assistant',
    specialty: 'Contract and compliance management',
  },
  {
    id: 'family-law',
    name: 'Family Law',
    slug: 'family-law',
    description: 'Discovery coordination, parenting plan preparation, financial disclosure organization, settlement negotiation support, and sensitive document management.',
    keyword: 'family law virtual assistant',
    specialty: 'Discovery and settlement coordination',
  },
  {
    id: 'immigration',
    name: 'Immigration Law',
    slug: 'immigration',
    description: 'Case tracking across multiple jurisdictions, visa application coordination, immigration deadline management, form preparation, and government correspondence management.',
    keyword: 'immigration law virtual assistant',
    specialty: 'Multi-jurisdictional case tracking',
  },
  {
    id: 'real-estate-law',
    name: 'Real Estate Law',
    slug: 'real-estate-law',
    description: 'Transaction coordination, closing document preparation, title research support, escrow management, and property record organization.',
    keyword: 'real estate law virtual assistant',
    specialty: 'Transaction and closing coordination',
  },
  {
    id: 'criminal-defense',
    name: 'Criminal Defense',
    slug: 'criminal-defense',
    description: 'Discovery management, hearing preparation, client communication, bail hearing coordination, and case file organization.',
    keyword: 'criminal defense virtual assistant',
    specialty: 'Discovery and hearing preparation',
  },
  {
    id: 'estate-planning',
    name: 'Estate Planning',
    slug: 'estate-planning',
    description: 'Client intake for estate planning, document preparation, trust administration support, probate coordination, and beneficiary communication.',
    keyword: 'estate planning virtual assistant',
    specialty: 'Probate and trust administration support',
  },
  {
    id: 'intellectual-property',
    name: 'Intellectual Property',
    slug: 'intellectual-property',
    description: 'Patent prosecution support, trademark filing coordination, licensing agreement management, and IP portfolio tracking.',
    keyword: 'intellectual property virtual assistant',
    specialty: 'Patent and trademark application support',
  },
];

export const competitors = [
  {
    id: 'smith-ai',
    name: 'Smith.ai',
    slug: 'smith-ai',
    priceRange: '$292.50-$1,170/mo',
    type: 'AI + Human Hybrid Receptionist',
    description: 'Smith.ai provides 24/7 legal intake and scheduling through AI and human hybrid receptionist services.',
    strengths: [
      '24/7 availability',
      'AI-powered call routing',
      'CRM integrations (Clio, Lawmatics)',
      'Bilingual options',
      'Call recording and analysis',
    ],
    weaknesses: [
      'Not dedicated (shared pool)',
      'Per-call pricing can be unpredictable',
      'Receptionist-only (no document prep or case management)',
      'AI sometimes creates confusion',
      'Limited customization',
    ],
    bestFor: 'Law firms needing 24/7 receptionist coverage',
  },
  {
    id: 'back-office-betties',
    name: 'Back Office Betties',
    slug: 'back-office-betties',
    priceRange: '$299-$1,199/mo',
    type: 'Legal Receptionist Service',
    description: 'Back Office Betties specializes in legal receptionist and intake services with live answering.',
    strengths: [
      'Legal-specific receptionist training',
      'Affordable entry point',
      'Bilingual options available',
      'Live answering during business hours',
      'Legal intake focus',
    ],
    weaknesses: [
      'Receptionist only (not full admin)',
      'Per-minute pricing can spike',
      'Not a dedicated person',
      'Limited to phone intake',
      'No document or case management',
    ],
    bestFor: 'Solo practitioners needing receptionist support',
  },
  {
    id: 'ruby-receptionists',
    name: 'Ruby Receptionists',
    slug: 'ruby-receptionists',
    priceRange: 'Starting ~$235/mo (50 minutes)',
    type: 'Virtual Receptionist',
    description: 'Ruby provides virtual receptionist and chat services, not legal-specific but widely used by law firms.',
    strengths: [
      'Professional brand recognition',
      'Well-established (20+ years)',
      'Multi-language support',
      'Chat and call services',
      'Affordable entry price',
    ],
    weaknesses: [
      'Generic (not legal-trained)',
      'Per-minute pricing unpredictable',
      'No legal-specific workflows',
      'No admin or document support',
      'Limited customization for law firms',
    ],
    bestFor: 'Firms wanting generic receptionist service',
  },
  {
    id: 'belay-legal',
    name: 'Belay Solutions',
    slug: 'belay-legal',
    priceRange: '$1,380+/mo',
    type: 'US-Based VA Service',
    description: 'Belay offers general VA support with some legal placements, US-based W-2 employees.',
    strengths: [
      'US-based team members',
      'Professional vetting',
      'Established company',
      'Flexible scaling',
      'W-2 employee model',
    ],
    weaknesses: [
      'Not legal-specialized',
      'Expensive ($1,380+ base)',
      '6-month minimum contract (lock-in)',
      'No legal software training',
      'Generic VA support',
    ],
    bestFor: 'Firms wanting US-based VA without legal focus',
  },
  {
    id: 'upwork',
    name: 'Upwork (Freelance Legal VAs)',
    slug: 'upwork',
    priceRange: 'Highly variable ($10-50+/hr)',
    type: 'Freelance Marketplace',
    description: 'Upwork connects firms with independent legal VA contractors worldwide.',
    strengths: [
      'Low rates possible',
      'Large talent pool',
      'Project-based pricing',
      'No long-term commitment',
      'Direct client-to-VA relationship',
    ],
    weaknesses: [
      'No vetting beyond reviews',
      'No background checks standard',
      'No NDA enforcement',
      'High turnover',
      'Quality inconsistency',
      'Confidentiality risks',
      'No Client Manager support',
    ],
    bestFor: 'Solo practitioners wanting to hire independently',
  },
];

export const tools = [
  {
    id: 'clio',
    name: 'Clio',
    slug: 'clio',
    category: 'Practice Management',
    description: 'The most widely-used practice management software for law firms.',
    vaSupport: 'Full integration - client intake, document management, billing, time tracking, matter management.',
    keyword: 'Clio virtual assistant',
  },
  {
    id: 'mycase',
    name: 'MyCase',
    slug: 'mycase',
    category: 'Practice Management',
    description: 'Cloud-based practice management system with strong document and case management.',
    vaSupport: 'Full integration - case management, documents, client communication, time entry, invoicing.',
    keyword: 'MyCase virtual assistant',
  },
  {
    id: 'practice-panther',
    name: 'PracticePanther',
    slug: 'practice-panther',
    category: 'Practice Management',
    description: 'All-in-one practice management for solos and small firms with affordable pricing.',
    vaSupport: 'Full integration - intake, documents, case management, billing, reporting.',
    keyword: 'PracticePanther virtual assistant',
  },
  {
    id: 'smokeball',
    name: 'Smokeball',
    slug: 'smokeball',
    category: 'Practice Management',
    description: 'Australian practice management software with global reach, strong on case management.',
    vaSupport: 'Full integration - documents, case tracking, client management, matter templates.',
    keyword: 'Smokeball virtual assistant',
  },
  {
    id: 'lawmatics',
    name: 'Lawmatics',
    slug: 'lawmatics',
    category: 'CRM & Client Intake',
    description: 'Legal CRM and client intake platform designed for lead capture and client management.',
    vaSupport: 'Intake automation, client communication, follow-up workflows, reporting.',
    keyword: 'Lawmatics virtual assistant',
  },
  {
    id: 'cosmolex',
    name: 'CosmoLex',
    slug: 'cosmolex',
    category: 'Practice Management',
    description: 'Practice management software with strong trust accounting and billing features.',
    vaSupport: 'Billing automation, time entry, matter management, trust accounting support.',
    keyword: 'CosmoLex virtual assistant',
  },
];

export const locations = {
  usa: [
    { city: 'New York', state: 'NY', timezone: 'EST', region: 'Northeast', paralegals: 60000, lawyers: 200000 },
    { city: 'Los Angeles', state: 'CA', timezone: 'PST', region: 'West', paralegals: 58000, lawyers: 210000 },
    { city: 'Chicago', state: 'IL', timezone: 'CST', region: 'Midwest', paralegals: 55000, lawyers: 190000 },
    { city: 'Houston', state: 'TX', timezone: 'CST', region: 'South', paralegals: 52000, lawyers: 180000 },
    { city: 'Phoenix', state: 'AZ', timezone: 'MST', region: 'Southwest', paralegals: 50000, lawyers: 170000 },
    { city: 'Philadelphia', state: 'PA', timezone: 'EST', region: 'Northeast', paralegals: 56000, lawyers: 185000 },
    { city: 'San Antonio', state: 'TX', timezone: 'CST', region: 'South', paralegals: 48000, lawyers: 165000 },
    { city: 'San Diego', state: 'CA', timezone: 'PST', region: 'West', paralegals: 54000, lawyers: 195000 },
    { city: 'Dallas', state: 'TX', timezone: 'CST', region: 'South', paralegals: 51000, lawyers: 175000 },
    { city: 'San Jose', state: 'CA', timezone: 'PST', region: 'West', paralegals: 62000, lawyers: 220000 },
    { city: 'Austin', state: 'TX', timezone: 'CST', region: 'South', paralegals: 50000, lawyers: 170000 },
    { city: 'Miami', state: 'FL', timezone: 'EST', region: 'Southeast', paralegals: 52000, lawyers: 180000 },
  ],
  uk: [
    { city: 'London', country: 'UK', timezone: 'GMT', paralegals: 45000, lawyers: 180000, regulator: 'SRA' },
    { city: 'Manchester', country: 'UK', timezone: 'GMT', paralegals: 38000, lawyers: 150000, regulator: 'SRA' },
    { city: 'Birmingham', country: 'UK', timezone: 'GMT', paralegals: 35000, lawyers: 140000, regulator: 'SRA' },
    { city: 'Edinburgh', country: 'UK', timezone: 'GMT', paralegals: 40000, lawyers: 155000, regulator: 'Law Society of Scotland' },
    { city: 'Cardiff', country: 'UK', timezone: 'GMT', paralegals: 34000, lawyers: 135000, regulator: 'Law Society of Wales' },
  ],
  middleEast: [
    { city: 'Dubai', country: 'UAE', timezone: 'GST', currency: 'AED', court: 'DIFC Courts' },
    { city: 'Abu Dhabi', country: 'UAE', timezone: 'GST', currency: 'AED', court: 'Federal Courts' },
    { city: 'Riyadh', country: 'Saudi Arabia', timezone: 'AST', currency: 'SAR', court: 'Saudi Courts' },
    { city: 'Doha', country: 'Qatar', timezone: 'AST', currency: 'QAR', court: 'Qatar Courts' },
  ],
  apac: [
    { city: 'Sydney', country: 'Australia', timezone: 'AEDT', currency: 'AUD', regulator: 'Law Society of NSW' },
    { city: 'Melbourne', country: 'Australia', timezone: 'AEDT', currency: 'AUD', regulator: 'Law Society of Victoria' },
    { city: 'Brisbane', country: 'Australia', timezone: 'AEST', currency: 'AUD', regulator: 'Law Society of Queensland' },
    { city: 'Auckland', country: 'New Zealand', timezone: 'NZDT', currency: 'NZD', regulator: 'Law Society of NZ' },
    { city: 'Wellington', country: 'New Zealand', timezone: 'NZDT', currency: 'NZD', regulator: 'Law Society of NZ' },
  ],
};

export const pricing = {
  partTime: {
    name: 'Part-Time',
    price: 700,
    currency: 'USD',
    period: '/month',
    hours: '20 hours/week',
    features: [
      'Dedicated VA assigned to your firm',
      'Up to 20 hours per week',
      'NDA and background verified',
      'Weekly reporting via Asana',
      'Backup VA during leave',
      'Cancel anytime',
    ],
  },
  fullTime: {
    name: 'Full-Time',
    price: 1300,
    currency: 'USD',
    period: '/month',
    hours: '40 hours/week',
    featured: true,
    features: [
      'Everything in Part-Time',
      'Up to 40 hours per week',
      'Priority VA matching',
      'Dedicated Client Manager',
      'Daily standups available',
      'Scale to multiple VAs',
    ],
  },
};

export const testimonials = [
  {
    quote: 'His practice runs like a firm three times its size. Same VA, two years running. No turnover, no retraining, no disruption.',
    author: 'Solo Attorney',
    specialty: 'Civil Litigation',
    metric: '3× operating capacity',
  },
  {
    quote: 'Client response time went from 48 hours to 2 hours. The VA handles intake now — we just practice law.',
    author: 'Managing Partner',
    specialty: 'Immigration Law',
    metric: '24× faster client response',
  },
  {
    quote: 'We scaled from 2 to 6 attorneys without hiring more admin staff. The VA is our operations backbone.',
    author: 'Practice Owner',
    specialty: 'Family Law',
    metric: '3× growth without overhead',
  },
];

export const salaryComparison = {
  paralegal: { min: 45000, max: 65000, title: 'Legal Paralegal' },
  legalSecretary: { min: 38000, max: 52000, title: 'Legal Secretary' },
  legalAdmin: { min: 35000, max: 48000, title: 'Legal Admin' },
  lawyerCapitalPartTime: { yearly: 8400, monthly: 700, title: 'Lawyer Capital VA (Part-Time)' },
  lawyerCapitalFullTime: { yearly: 15600, monthly: 1300, title: 'Lawyer Capital VA (Full-Time)' },
};

export const blogPosts = [
  {
    slug: 'legal-va-cost',
    title: 'How Much Does a Legal Virtual Assistant Cost in 2025?',
    excerpt: 'Breaking down the true cost of legal VA services vs paralegal hire',
    keyword: 'legal virtual assistant cost',
  },
  {
    slug: 'solo-attorney-va',
    title: 'The Solo Attorney\'s Guide to Hiring a Virtual Assistant',
    excerpt: 'Step-by-step guide to implementing VA support in your solo practice',
    keyword: 'solo attorney virtual assistant',
  },
  {
    slug: 'client-intake-best-practices',
    title: 'Client Intake Best Practices: How Law Firms Convert More Consultations',
    excerpt: 'Systemize intake to convert more consultations into retained clients',
    keyword: 'law firm client intake',
  },
  {
    slug: 'clio-va-guide',
    title: 'Clio Virtual Assistant: Getting the Most from Your Practice Management Software',
    excerpt: 'How VAs can unlock Clio\'s full potential for your firm',
    keyword: 'Clio virtual assistant',
  },
  {
    slug: 'legal-document-preparation',
    title: 'Legal Document Preparation: What a VA Can (and Cannot) Handle',
    excerpt: 'Understanding the scope of document support from your VA',
    keyword: 'legal document preparation virtual assistant',
  },
  {
    slug: 'legal-secretary-turnover',
    title: 'The True Cost of Legal Secretary Turnover (And the Alternative)',
    excerpt: 'Why hiring a VA is better than the constant cycle of staff turnover',
    keyword: 'legal secretary turnover cost',
  },
  {
    slug: 'immigration-law-va',
    title: 'Virtual Assistants for Immigration Law: Managing Cases Across Borders',
    excerpt: 'Multi-jurisdictional case tracking and coordination for immigration practices',
    keyword: 'immigration law virtual assistant',
  },
  {
    slug: 'small-firm-va',
    title: 'How Small Firms Compete with Big Law Using Virtual Assistants',
    excerpt: 'Operations strategy for small firms to scale without overhead',
    keyword: 'small law firm virtual assistant',
  },
  {
    slug: 'vs-smith-ai',
    title: 'Smith.ai vs Lawyer Capital VA: Receptionist Service vs Dedicated VA',
    excerpt: 'Comparing receptionist services to dedicated VA support',
    keyword: 'Smith.ai alternative',
  },
  {
    slug: 'attorney-delegate-tasks',
    title: '5 Tasks Every Attorney Should Delegate Today',
    excerpt: 'The highest-impact admin tasks to hand off to a VA',
    keyword: 'tasks to delegate attorney',
  },
];
